### ISSUE TITLE
Do you have an introduction blog about the principles of your code?

### ISSUE THREAD

**Issue by changjiezhou1** [julwil/chameleon_hash#1]
Thank you very much for providing such an implementation of chameleon hash, but in the process of understanding the code idea, I don't quite understand the meaning of the variables in your code, which is different from the related papers I read. Is there any relevant blog or document to introduce your code?

**Comment by julwil** [comment]
> Thank you very much for providing such an implementation of chameleon hash, but in the process of understanding the code idea, I don't quite understand the meaning of the variables in your code, which is different from the related papers I read. Is there any relevant blog or document to introduce your code?

Thanks for reaching out. Here's the [thesis](https://www.merlin.uzh.ch/contributionDocument/download/13762) the implementation is built for. Relevant section (2.4.1). 
The implementation is based on [Ateniese et. al's](https://eprint.iacr.org/2004/243.pdf) paper.

**Comment by changjiezhou1** [comment]
Thank you!




天照
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "julwil/chameleon_hash"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月21日(星期六) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [julwil/chameleon_hash] Do you have an introduction blog about the principles of your code? (Issue #1)





  
Thank you very much for providing such an implementation of chameleon hash, but in the process of understanding the code idea, I don't quite understand the meaning of the variables in your code, which is different from the related papers I read. Is there any relevant blog or document to introduce your code?
  
Thanks for reaching out. Here's the thesis the implementation is built for. Relevant section (2.4.1).
 The implementation is based on Ateniese et. al's paper.
